"""Unit tests for the new ICT primitives (engines/ict/primitives.py).

Run standalone (inside the backend container / image):
    pytest backend/tests/test_ict_primitives.py -v -p no:cacheprovider

These primitives are PURE and not yet used by any strategy, so these tests are
self-contained and fast. Covers: detect_mss (reversal up), detect_bos
(with-trend continuation), session_range (ET window high/low), ote_levels
(0.705 focal level), price_in_fvg, and the new is_in_session killzone keys.

The OHLC arrays below were generated by a zig-zag builder and verified so that
each pivot is a strict +-3 swing extreme that find_swing_highs/lows detects;
they are baked verbatim for determinism.
"""
import pandas as pd
import pytest

from app.engines.ict.primitives import (
    detect_mss, detect_bos, session_range, ote_levels, price_in_fvg,
    is_in_session, FairValueGap, MSS, BOS,
)

ET = "America/New_York"


def _df(rows, start="2024-03-04 09:30", freq="1min", tz="UTC"):
    idx = pd.date_range(start=start, periods=len(rows), freq=freq, tz=tz)
    return pd.DataFrame(rows, index=idx, columns=["open", "high", "low", "close", "volume"])


# A clean DOWNtrend (descending swing highs ~101.5/97.5/93.5, descending swing
# lows ~90.5/86.5/82.5) followed by a large bullish displacement bar (idx 29)
# that closes above the most-recent swing high (93.5) -> bullish MSS.
_DOWN_ROWS = [
    [100.0, 100.3, 99.7, 100.0, 1000], [100.0, 100.3, 99.7, 100.0, 1001],
    [100.0, 100.3, 99.7, 100.0, 1002], [100.0, 100.3, 99.7, 100.0, 1003],
    [99.5, 101.5, 99.8, 101.0, 1004], [98.0, 98.3, 97.7, 98.0, 1005],
    [96.0, 96.3, 95.7, 96.0, 1006], [94.0, 94.3, 93.7, 94.0, 1007],
    [92.5, 92.2, 90.5, 91.0, 1008], [93.0, 93.3, 92.7, 93.0, 1009],
    [94.0, 94.3, 93.7, 94.0, 1010], [95.0, 95.3, 94.7, 95.0, 1011],
    [95.5, 97.5, 95.8, 97.0, 1012], [94.0, 94.3, 93.7, 94.0, 1013],
    [92.0, 92.3, 91.7, 92.0, 1014], [90.0, 90.3, 89.7, 90.0, 1015],
    [88.5, 88.2, 86.5, 87.0, 1016], [89.0, 89.3, 88.7, 89.0, 1017],
    [90.0, 90.3, 89.7, 90.0, 1018], [91.0, 91.3, 90.7, 91.0, 1019],
    [91.5, 93.5, 91.8, 93.0, 1020], [90.0, 90.3, 89.7, 90.0, 1021],
    [88.0, 88.3, 87.7, 88.0, 1022], [86.0, 86.3, 85.7, 86.0, 1023],
    [84.5, 84.2, 82.5, 83.0, 1024], [84.0, 84.3, 83.7, 84.0, 1025],
    [84.0, 84.3, 83.7, 84.0, 1026], [84.0, 84.3, 83.7, 84.0, 1027],
    [84.0, 84.3, 83.7, 84.0, 1028], [84.0, 95.0, 83.5, 94.0, 5000],
]

# A clean UPtrend (ascending swing highs ~85.5/89.5/93.5, ascending swing lows
# ~80.5/84.5/88.5) followed by a bar (idx 29) that closes above the most-recent
# swing high (93.5) -> with-trend BOS up.
_UP_ROWS = [
    [84.0, 84.3, 83.7, 84.0, 1000], [84.0, 84.3, 83.7, 84.0, 1001],
    [84.0, 84.3, 83.7, 84.0, 1002], [84.0, 84.3, 83.7, 84.0, 1003],
    [83.5, 85.5, 83.8, 85.0, 1004], [83.5, 83.8, 83.2, 83.5, 1005],
    [83.0, 83.3, 82.7, 83.0, 1006], [82.5, 82.8, 82.2, 82.5, 1007],
    [82.5, 82.2, 80.5, 81.0, 1008], [83.5, 83.8, 83.2, 83.5, 1009],
    [85.0, 85.3, 84.7, 85.0, 1010], [86.5, 86.8, 86.2, 86.5, 1011],
    [87.5, 89.5, 87.8, 89.0, 1012], [87.5, 87.8, 87.2, 87.5, 1013],
    [87.0, 87.3, 86.7, 87.0, 1014], [86.5, 86.8, 86.2, 86.5, 1015],
    [86.5, 86.2, 84.5, 85.0, 1016], [87.5, 87.8, 87.2, 87.5, 1017],
    [89.0, 89.3, 88.7, 89.0, 1018], [90.5, 90.8, 90.2, 90.5, 1019],
    [91.5, 93.5, 91.8, 93.0, 1020], [91.5, 91.8, 91.2, 91.5, 1021],
    [91.0, 91.3, 90.7, 91.0, 1022], [90.5, 90.8, 90.2, 90.5, 1023],
    [90.5, 90.2, 88.5, 89.0, 1024], [90.0, 90.3, 89.7, 90.0, 1025],
    [90.0, 90.3, 89.7, 90.0, 1026], [90.0, 90.3, 89.7, 90.0, 1027],
    [90.0, 90.3, 89.7, 90.0, 1028], [90.0, 95.0, 89.5, 94.0, 4000],
]


# ---------------------------------------------------------------------------
# detect_mss - reversal up.
# ---------------------------------------------------------------------------
def test_detect_mss_reversal_up():
    df = _df([list(r) for r in _DOWN_ROWS])
    mss = detect_mss(df, lookback=3)
    assert isinstance(mss, MSS), f"expected an MSS, got {mss!r}"
    assert mss.direction == "up", f"expected bullish reversal, got {mss.direction}"
    assert mss.prior_trend == "down"
    assert mss.bar_index == len(df) - 1
    # Broke the most-recent counter-trend swing HIGH (~93.5).
    assert mss.broken_level == pytest.approx(93.5)


def test_detect_mss_none_on_continuation():
    """A downtrend that keeps drifting down (no reclaim) -> no MSS."""
    rows = [list(r) for r in _DOWN_ROWS]
    rows[-1] = [84.0, 84.3, 82.0, 83.0, 100]  # small bearish bar, no reclaim
    assert detect_mss(_df(rows), lookback=3) is None


def test_detect_mss_requires_displacement():
    """Reclaim above the swing high but WITHOUT displacement -> no MSS.

    Close just above 93.5 on a tiny-range bar (fails the body/range gate)."""
    rows = [list(r) for r in _DOWN_ROWS]
    rows[-1] = [93.6, 93.8, 93.5, 93.7, 100]  # above 93.5 but tiny range
    assert detect_mss(_df(rows), lookback=3) is None


# ---------------------------------------------------------------------------
# detect_bos - continuation up.
# ---------------------------------------------------------------------------
def test_detect_bos_continuation_up():
    df = _df([list(r) for r in _UP_ROWS])
    bos = detect_bos(df, lookback=3)
    assert isinstance(bos, BOS), f"expected a BOS, got {bos!r}"
    assert bos.direction == "up"
    assert bos.trend == "up"
    assert bos.bar_index == len(df) - 1
    assert bos.broken_level == pytest.approx(93.5)


def test_detect_bos_none_without_break():
    rows = [list(r) for r in _UP_ROWS]
    rows[-1] = [90.0, 90.3, 89.2, 90.0, 100]  # stays below the swing high
    assert detect_bos(_df(rows), lookback=3) is None


# ---------------------------------------------------------------------------
# session_range - high/low of bars inside an ET window.
# ---------------------------------------------------------------------------
def test_session_range_window_high_low():
    # 30-min bars across a full UTC day; inject a clear high/low ONLY inside
    # 10:00-11:00 ET (the 10:00 and 10:30 ET bars).
    idx = pd.date_range(start="2024-03-04 00:00", periods=48, freq="30min", tz="UTC")
    rows = []
    for ts in idx:
        et = ts.tz_convert(ET)
        if et.hour == 10 and et.minute == 0:
            rows.append([100, 110, 99, 105, 1])     # window HIGH = 110
        elif et.hour == 10 and et.minute == 30:
            rows.append([105, 106, 90, 95, 1])        # window LOW = 90
        else:
            rows.append([100, 101, 99, 100, 1])
    df = pd.DataFrame(rows, index=idx, columns=["open", "high", "low", "close", "volume"])

    hi, lo = session_range(df, "10:00", "11:00")
    assert hi == 110.0
    assert lo == 90.0

    # A window with NO bars (between the :00 and :30 marks) -> (None, None).
    assert session_range(df, "10:05", "10:25") == (None, None)


def test_session_range_accepts_time_tuples():
    idx = pd.date_range(start="2024-03-04 00:00", periods=48, freq="30min", tz="UTC")
    rows = []
    for ts in idx:
        et = ts.tz_convert(ET)
        rows.append([100, 120 if et.hour == 14 else 101, 80 if et.hour == 14 else 99, 100, 1])
    df = pd.DataFrame(rows, index=idx, columns=["open", "high", "low", "close", "volume"])
    hi, lo = session_range(df, (14, 0), (15, 0))
    assert hi == 120.0 and lo == 80.0


def test_session_range_empty_frame():
    assert session_range(pd.DataFrame(), "10:00", "11:00") == (None, None)


# ---------------------------------------------------------------------------
# ote_levels - 0.705 focal level lands at the right price.
# ---------------------------------------------------------------------------
def test_ote_levels_bullish():
    # Impulse low->high 100 -> 200 (leg = 100). Long retraces DOWN from 200.
    lv = ote_levels(swing_high=200.0, swing_low=100.0, direction="long")
    assert lv[0.62] == pytest.approx(138.0)
    assert lv[0.705] == pytest.approx(129.5)
    assert lv[0.79] == pytest.approx(121.0)
    assert lv["entry"] == pytest.approx(129.5)
    assert lv["direction"] == "long"


def test_ote_levels_bearish():
    lv = ote_levels(swing_high=200.0, swing_low=100.0, direction="short")
    assert lv[0.705] == pytest.approx(170.5)
    assert lv["entry"] == pytest.approx(170.5)
    assert lv["direction"] == "short"


# ---------------------------------------------------------------------------
# price_in_fvg
# ---------------------------------------------------------------------------
def test_price_in_fvg():
    fvg = FairValueGap(direction="bullish", high=110.0, low=100.0, midpoint=105.0,
                       bar_index=5, timestamp=pd.Timestamp("2024-01-01"), size_ticks=40,
                       ce_level=105.0)
    assert price_in_fvg(105.0, fvg) is True
    assert price_in_fvg(100.0, fvg) is True   # inclusive edge
    assert price_in_fvg(111.0, fvg) is False
    assert price_in_fvg(100.0, fvg, inclusive=False) is False
    assert price_in_fvg(100.0, None) is False


# ---------------------------------------------------------------------------
# New killzone session keys via the (extended) is_in_session.
# ---------------------------------------------------------------------------
def _at_et(hour, minute=0):
    """A tz-aware UTC timestamp that maps to the given ET wall-clock.

    Build the instant in America/New_York (handles day rollover for late/early
    hours) then convert to UTC, so the engine's is_in_session reproduces the
    intended ET hour regardless of DST.
    """
    naive = pd.Timestamp(f"2024-03-04 {hour:02d}:{minute:02d}")
    return naive.tz_localize(ET).tz_convert("UTC")


@pytest.mark.parametrize("key,inside,outside", [
    ("SILVER_BULLET", (10, 30), (9, 30)),
    ("NY_OPEN", (9, 45), (10, 15)),
    ("NY_PM_ICT", (14, 0), (13, 0)),
    ("LONDON_OPEN", (2, 30), (3, 30)),
])
def test_new_session_keys(key, inside, outside):
    assert is_in_session(_at_et(*inside), [key]) is True
    assert is_in_session(_at_et(*outside), [key]) is False


def test_existing_session_keys_unchanged():
    # Regression: the original keys still behave as before.
    assert is_in_session(_at_et(10, 0), ["NY_AM"]) is True      # 10:00 in 09:30-12:00
    assert is_in_session(_at_et(14, 30), ["NY_PM"]) is True     # 14:30 in 14:00-15:00
    assert is_in_session(_at_et(13, 0), ["NY_PM"]) is False
    assert is_in_session(_at_et(3, 0), ["LONDON"]) is True      # 03:00 in 02:00-05:00
    assert is_in_session(_at_et(21, 0), ["ASIA"]) is True       # 21:00 in 20:00-24:00
